name: DentistManager

volumes:
  dentist_manager_data:

services:
  postgres:
    container_name: DentistManager
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DentistManager
    ports:
      - "5432:5432"
    volumes:
      - dentist_manager_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 15s
      retries: 3
      
      
    